### ISSUE TITLE
Motivo Code

### ISSUE THREAD

**Issue by kakodkar** [Steven--/graphlets#1]
Hi!
The link you've provided to the bitbucket repo for Motivo is broken, could you please provide me with a new link?

**Comment by Steven--** [comment]
Sorry about that. The link pointed to a mercurial repository hosted on Bitbucket. When Butbucket removed mercurial support the repository was migrated to git and is now hosted on Gitlab. You can find it at https://gitlab.com/steven3k/motivo 

I have now updated the README.md file. Sorry for the inconvenience.

**Comment by kakodkar** [comment]
Thanks so much Steven!
